export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: '1rem' }}>
          <h1>My Website</h1>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: '1rem' }}>
          <p>&copy; 2025 My Website. All Rights Reserved.</p>
        </footer>
      </body>
    </html>
  )
}
