export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderLayout />
        {children}
        <FooterLayout />
      </body>
    </html>
  )
}

function HeaderLayout() {
  return (
    <header style={{
      backgroundColor: "lightblue",
      padding: '1rem',
      textAlign: "center"
    }}>
      <h1>My Website</h1>
    </header>
  )
}

function FooterLayout() {
  return (
    <footer style={{
      backgroundColor: "ghostwhite",
      padding: '1rem',
      textAlign: "center"
    }}>
      <p>&copy; 2025 My Website. All Rights Reserved.</p>
    </footer>
  )
}
